name: Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  MODULE_NAME: luaerror
  DEPENDENCIES: ./dependencies
  GARRYSMOD_COMMON: ./dependencies/garrysmod_common
  GARRYSMOD_COMMON_BRANCH: x86-64-support-sourcesdk
  GARRYSMOD_COMMON_REPOSITORY: https://github.com/danielga/garrysmod_common.git
  PROJECT_GENERATOR_VERSION: 3
  REPOSITORY_DIR: .

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release

  build_linux:
    needs: [create_release]
    runs-on: ubuntu-latest
    env:
      BOOTSTRAP_URL: https://raw.githubusercontent.com/danielga/garrysmod_common/master/build/bootstrap.sh
      BUILD_SCRIPT: ./dependencies/garrysmod_common/build/build.sh
      COMPILER_PLATFORM: gmake
      PREMAKE5: ./dependencies/linux/premake-core/premake5
      PROJECT_OS: linux
      PREMAKE5_URL: https://github.com/danielga/garrysmod_common/releases/download/premake-build%2F5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          set -ex
          sudo apt-get -y install gcc-multilib g++-multilib libstdc++-9-dev
          curl -f -s -L "$BOOTSTRAP_URL" | bash -x
          $BUILD_SCRIPT
      - name: Upload release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          fail_on_unmatched_files: true
          files: "**/Release/**/*.dll"